import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { FloatingDockDemo } from "../components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between bg-black m-0 p-0">
          {children}

          {/* Desktop image */}
          <div className="hidden md:block fixed bottom-0 sm:left-[-50%] md:left-[-50%] lg:left-[-20%] overflow-hidden shadow-lg filter grayscale p-0 m-0">
            <img
              src="./Adi-transformed.png"
              alt="Hero"
              width={1100}
              height={1100}
              draggable="false"
              style={{ userSelect: "none", pointerEvents: "none" }}
            />
          </div>

          <FloatingDockDemo />
        </main>
      </body>
    </html>
  );
}
